vich_uploader:
    db_driver: orm

    mappings:
        product_image:
            uri_prefix: /images/logements
            upload_destination: '%kernel.project_dir%/public/images/logements'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
